# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JCPhotoBrowse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'JCH5Bridge'
    pod 'YBImageBrowser'
  # Pods for JCPhotoBrowse

  target 'JCPhotoBrowseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JCPhotoBrowseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
